name: Question
description: Ask a question about usage or configuration
title: "[Question] Describe your question"
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What are you trying to do or figure out?
      placeholder: Ask your question here.
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
      placeholder: e.g. 1.21.1
